apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-cicd-app
  template:
    metadata:
      labels:
        app: python-cicd-app
    spec:
      containers:
        - name: python-cicd-app
          image: mahesh/python-cicd:latest   # replace with your DockerHub repo
          ports:
            - containerPort: 5000
